### ISSUE TITLE
Tried to build on MacOS (10.12.3) and failed ...

### ISSUE THREAD

**Issue by webarchymeta** [markandrus/build-webrtc#3]
Here is what I got when run `npm install build-webrtc`

```
Syncing projects: 100% (2/2), done.                      

________ running '/usr/bin/python -c import os,sys;script = os.path.join("trunk","check_root_dir.py");_ = os.system("%s %s" % (sys.executable,script)) if os.path.exists(script) else 0' in '/Users/macuser/develop/node_modules/build-webrtc/webrtc'

________ running '/usr/bin/python -u src/sync_chromium.py --target-revision 1008ac1d53cacb04418ec3f3da9269e2287b0a7f' in '/Users/macuser/develop/node_modules/build-webrtc/webrtc'
+---------------------------------------------------------------------+
| NOTICE: This sync of Chromium will take a long time as several      |
|         gigabytes of data are downloaded. If this is your initial   |
|         sync and it's interrupted, try running 'gclient sync' again.|
|         If that fails, wipe everything clean and start over again.  |
+---------------------------------------------------------------------+
Running "gclient sync --force --revision src@1008ac1d53cacb04418ec3f3da9269e2287b0a7f -v --gclientfile .gclient.tmp --delete_unversioned_trees --reset --upstream --deps=mac" in /Users/macuser/develop/node_modules/build-webrtc/webrtc/src/chromium
Traceback (most recent call last):
  File "src/sync_chromium.py", line 195, in <module>
    sys.exit(main())
  File "src/sync_chromium.py", line 186, in main
    ret = subprocess.call(args, cwd=opts.chromium_dir, env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error: Command '/usr/bin/python -u src/sync_chromium.py --target-revision 1008ac1d53cacb04418ec3f3da9269e2287b0a7f' returned non-zero exit status 1 in /Users/macuser/develop/node_modules/build-webrtc/webrtc
jake aborted.
Error: Command failed: /Users/macuser/develop/node_modules/build-webrtc/depot_tools/gclient sync --force --with_branch_heads
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
(See full trace by running task with --trace)
```

**Comment by marmos91** [comment]
Same problem here. Have you found any solution?

**Comment by webarchymeta** [comment]
not yet ...

**Comment by 493326889** [comment]
Same . have any solution?

**Comment by markandrus** [comment]
I think the `PATH` needs to be set correctly (it's not including `gclient`, part of `depot_tools`). Sorry about that. This seems to work:

```
$ PATH="$(pwd)/depot_tools:$PATH" npm install
```

**Comment by schrockwell** [comment]
And for packages that depend on `build-webrtc` (such as `wrtc-full`), you want to do, instead:

```
$ PATH="$(pwd)/node_modules/build-webrtc/depot_tools:$PATH" npm install
```
